version: "3"
services:

  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    env_file: .env
    volumes:
      - db:/app/db

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - ${PORT}:${PORT}
    env_file: .env
    volumes:
      - db:/app/db

volumes:
  devdb:
