version: "3"
services:

  devbot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    env_file: .env
    volumes:
      - devdb:/app/db # DEV

  devweb:
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - ${PORT}:${PORT}
    env_file: .env
    volumes:
      - devdb:/app/db # DEV

volumes:
  devdb: # DEV
