version: "3"
services:

  poggersbot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    env_file: .env
    volumes:
      - db:/app/db

  poggersweb:
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - ${PORT}:${PORT}
    networks:
      - caddy_network
    env_file: .env
    volumes:
      - db:/app/db
      - ./:/app

volumes:
  db:

networks:
  caddy_network:
    external: true
