version: "3"
services:

  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    env_file: .env
    volumes:
      - db:/app/db

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - "7777:7777"
    env_file: .env
    volumes:
      - db:/app/db

volumes:
  db:
